# Generated by Django 5.0.1 on 2024-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='userType',
            field=models.CharField(choices=[('Employee', 'EMPLOYEE'), ('Employer', 'EMPLOYER')], default='EMPLOYEE', max_length=10),
        ),
    ]
